### ISSUE TITLE
[NPC] Альсен Пери

### ISSUE THREAD

**Issue by EndarValuk** [EugVV/TToN-ru-unof#2]
Почему-то персонаж сообщает что он ***Хиург***, а не **Хирург**.
Хотя, возможно, специфика?

![PXL_20220905_140158485](https://user-images.githubusercontent.com/4099836/188504282-6f72499a-27ef-4b1d-b8fc-b5b635059f0d.jpg)
![PXL_20220905_140313607](https://user-images.githubusercontent.com/4099836/188504306-63bcfc7e-995a-4cd4-9f38-0d6d229ff137.jpg)

**Comment by EugVV** [comment]
Всё правильно, это терминология Нуменеры. Так тут называются целители, которые используют нуменеры. Chiurgeon (не chirurgeon и не surgeon). [Вот](https://numenera.fandom.com/wiki/Truth) некоторые распространённые термины.
